version: "3.7"
services:
    app:
        build:
            args:
                user: me
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        container_name: wimm-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    db:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: wimm-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d

    phpmyadmin:
        platform: linux/x86_64
        image: phpmyadmin/phpmyadmin:latest
        restart: unless-stopped
        container_name: wimm-pma
        depends_on:
            - db
        environment:
            PMA_HOST: db
        ports:
            - '9000:80'

    nginx:
        image: nginx:alpine
        container_name: wimm-nginx
        restart: unless-stopped
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
